config/routes.rb
Rails.application.routes.draw do
	resources :tasks
	post 'tasks/:id' => 'tasks#find_by_category'
	root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :item, presence: true
	validates :due_date, presence: true
	validates :category, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@task = Task.new
		@tasks = Task.all
	end

	def create
		Task.create(task_params)
		redirect_to root_path
	end

	def new
	end

	def edit
		@tasks = Task.all
		@task = Task.find(params[:id])
	end

	def update
		task = Task.find(params[:id])
		task.update_attributes(task_params)
		redirect_to root_path
	end

	def find_by_category
		@cat_task = Task.find(params[:id])
		@tasks = Task.where("category = ?", @cat_task.category)
		render "index"
	end

	def destroy
		Task.destroy(params[:id])
		redirect_to root_path
	end

	def task_params
		params.require(:task).permit(:due_date, :item, :category)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<% @version = "v0.1 Matt Weidner <jopawp@gmail.com>" %>
<!DOCTYPE html>
<html>
<head>
  <title>Todo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Todo</h1>
<h4><%= @version %></h4>
<hr />

<%= yield %>

</body>
</html>

app/views/tasks/_form.html.erb
<% if @task != nil %>
	<%= form_for @task do |f|  %>
	<table>
		<tr>
			<th>Category</th>
			<th>Task</th>
			<th>Due Date</th>
		</tr>
		<tr>
			<td><%= f.text_field :category  %></td>
			<td><%= f.text_field :item  %></td>
			<td><%= f.date_field :due_date  %></td>
			<td><%= f.submit %></td>
		</tr>
	</table>
	<%  end %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/index.html.erb
<p>
	<% @task = Task.new %>
	<%= render "form" %>
</p>
<% if @tasks.count != 0 %>
	<table>
		<tr>
			<th>Created</th>
			<th>Task</th>
			<th>Category</th>
			<th>Due Date</th>
			<th></th>
			<th></th>
		</tr>
	<% @tasks.each do |t|  %>
		<tr>
			<td><%= t.created_at %></td>
			<td><%= t.item %></td>
			<td><%= link_to t.category, t, method: :find_by_category %></td>
			<td><%= t.due_date %></td>
			<td><%= link_to "Edit", edit_task_path(t) %></td>
			<td><%= link_to "Remove", t, method: :delete, data: { confirm: "Are you sure?" } %></td>
		</tr>
	<%  end %>
	</table>
<% else %>
	<p>No todo items found.</p>
<% end %>